= Getting started
:output-html:

Before you start using Siren Platform, we recommend that you watch the
https://www.youtube.com/watch?v=ah0iogZn1lg[introductory video].

You can experience Siren Platform easily by using one of our
non-production distributions:

* If you want to load data yourself, download the
https://siren.io/downloads?product=siren-platform[Siren Platform - Easy
start] package and follow the instructions in the
https://docs.google.com/document/d/1lRVII4OQiCIaCZJ4M57ykRro45S1QuhRruT1XhMiuTE[Getting
started tutorial]. This tutorial shows you how to configure dashboards
and visualizations.
* If you want a fully-loaded and configured experience, download the
https://siren.io/downloads?product=siren-platform-demo-data[Siren
Platform - A preloaded demo] package and follow the instructions in
ifdef::output-pdf[<<getting-started-with-demo-data.adoc#,Getting started with demo data>>]
ifdef::output-html[xref:getting-started-with-demo-data.adoc[Getting started with demo data]]
.

If you are ready to use Siren Platform in a production environment, follow the instructions in
ifdef::output-pdf[<<module-siren-investigate/pages/setting-up-siren-investigate.adoc#,Setting up Siren Investigate>>]
ifdef::output-html[xref:module-siren-investigate:setting-up-siren-investigate.adoc[Setting up Siren Investigate]]
.
