= Getting Started

In this short guide, you will learn how you can quickly install the Siren Federate plugin in Elasticsearch,
load two collections of documents inter-connected by a common attribute, and execute a relational query across
the two collections within the Elasticsearch environment.

== Prerequisites

This guide requires that you have downloaded and
installed the https://www.elastic.co/downloads/elasticsearch[Elasticsearch {elasticsearch-version}] distribution
on your computer. If you do not have an Elasticsearch distribution, you can run the following
commands:

[source,bash,subs=attributes+]
-----------------------------------------------------------
$ wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{elasticsearch-version}.zip
$ unzip elasticsearch-{elasticsearch-version}.zip
$ cd elasticsearch-{elasticsearch-version}
-----------------------------------------------------------

If you plan to use `{sg}` for securing your cluster, then you need to download the Apache-licensed Elasticsearch bundle instead at https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-{elasticsearch-version}.zip.

== Installing the Siren Federate Plugin

Before starting Elasticsearch, you have to install the Siren Federate plugin. Assuming that you are in your Elasticsearch
installation directory, you can run the following command:

[source,bash,subs=attributes+]
-----------------------------------------------------------
$ ./bin/elasticsearch-plugin install file:///PATH-TO-SIREN-FEDERATE-PLUGIN/siren-federate-{elasticsearch-version}-{siren-version}-plugin.zip
-> Downloading file:///PATH-TO-SIREN-FEDERATE-PLUGIN/siren-federate-{elasticsearch-version}-{siren-version}-plugin.zip
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission cloudera.properties read
* java.io.FilePermission simba.properties read
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.misc.*
* java.lang.RuntimePermission accessClassInPackage.sun.security.provider
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
...
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed siren-federate
-----------------------------------------------------------

In case you want to remove the plugin, you can run the following command:

[source,bash]
-----------------------------------------------------------
$ bin/elasticsearch-plugin remove siren-federate

-> Removing siren-federate...
Removed siren-federate
-----------------------------------------------------------

== Starting Elasticsearch

To launch Elasticsearch, run the following command:

[source,bash]
-----------------------------------------------------------
$ ./bin/elasticsearch
-----------------------------------------------------------

In the output, you should see a line like the following which indicates that the Siren Federate plugin is installed and
running:
-----------------------------------------------------------
[2017-04-11T10:42:02,209][INFO ][o.e.p.PluginsService     ] [etZuTTn] loaded plugin [siren-federate]
-----------------------------------------------------------

