= Query Planning & Optimisation

The coordinator node is leveraging Apache Calcite for planning the job execution. A search request is first parsed
into an abstract syntax tree before being transformed into a logical relational plan. A set of rules will then be
applied to optimise the logical plan. We leverage both the Hep and Volcano engine to optimise the logical plan
using heuristic and statistical information. The logical plan is then transformed into a physical plan before being
executed.

The physical plan represents a tree of tasks to be executed. The coordinator will try to execute tasks concurrently
when possible. In the previous example, the two `Search/Project` tasks are executed concurrently, and the
`Hash Join` task is executed only after the completion of the two `Search/Project` tasks.

When handling a multi search request, each request will be planned separately, each one producing a physical plan.
However, before the execution of the physical plans, the planner will combine all the physical plans into a single
one, by mapping identical operations to one single task. We can see that as a step to fold multiple trees of tasks into
a single directed graph model, where overlapping operations across trees will become one single vertex in the graph.
This is useful to reuse computation across multiple requests.
